### ISSUE TITLE
Support code generation for inline schema definitions (request & response body)

### ISSUE THREAD

**Issue by VictorKrapivin** [itroadlabs/apicross#4]
At the moment constructions like below are not supported:

```yaml
responses:
   '200':
      description: ...
      content:
         application/json:
            schema:
               type: array
               items:
                   type: string     
```
But sometimes for simple cases such definitions are very useful

**Comment by VictorKrapivin** [comment]
Implemented limited support for following cases:
```yaml
      content:
         application/json:
            schema:
               type: array
               items:
                   type: <any primitive type>
```
and
```yaml
      content:
         application/json:
            schema:
               type: array
               items:
                   $ref: <any ref>
```
and
```yaml
      content:
         application/json:
            schema:
               type: <any primitive type>
```
